/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Transporte;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import BL.GestionPaquete.Paquete;
import BL.Transporte.Vehiculo;

//import BL.Transporte.Vehiculo;

/**
 *
 * @author dell
 */
public class UICamionCargaDespachar extends javax.swing.JPanel {

    Vehiculo vehiculo = new Vehiculo();
    /**
     * Creates new form UITransportePaquetes
     */
    public UICamionCargaDespachar() {
        initComponents();
       // List paquete =    vehiculo.listarPaquetes("En Transito")       
    // obtener la lista de "En transito" y cargar en tabla 1
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondoTUIP = new javax.swing.JPanel();
        ImgCamionTUIP = new javax.swing.JLabel();
        txtCapacidadP = new javax.swing.JLabel();
        TxtCamion = new javax.swing.JLabel();
        txtCamionP = new javax.swing.JLabel();
        TablaEntregarPaquete = new javax.swing.JScrollPane();
        TablaListaInventarioCamionC = new javax.swing.JTable();
        btnEntregarPaquetesCC = new javax.swing.JButton();
        btnRefreshCC = new javax.swing.JToggleButton();

        PanelFondoTUIP.setBackground(new java.awt.Color(37, 98, 234));
        PanelFondoTUIP.setForeground(new java.awt.Color(37, 98, 234));

        ImgCamionTUIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Transporte/Imagenes/camion.jpg"))); // NOI18N

        txtCapacidadP.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidadP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtCapacidadP.setForeground(new java.awt.Color(255, 255, 255));

        TxtCamion.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        TxtCamion.setForeground(new java.awt.Color(255, 255, 255));
        TxtCamion.setText("CAMIÓN CARGA");

        javax.swing.GroupLayout PanelFondoTUIPLayout = new javax.swing.GroupLayout(PanelFondoTUIP);
        PanelFondoTUIP.setLayout(PanelFondoTUIPLayout);
        PanelFondoTUIPLayout.setHorizontalGroup(
            PanelFondoTUIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoTUIPLayout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(ImgCamionTUIP)
                .addGap(70, 70, 70))
            .addGroup(PanelFondoTUIPLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelFondoTUIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCamion)
                    .addComponent(txtCapacidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        PanelFondoTUIPLayout.setVerticalGroup(
            PanelFondoTUIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoTUIPLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ImgCamionTUIP)
                .addGap(40, 40, 40)
                .addComponent(TxtCamion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCapacidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        txtCamionP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtCamionP.setText("CAMIÓN");

        TablaListaInventarioCamionC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Paquete", "Peso", "Tamanio", "Remitente", "Agencia Origen", "Agencia Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaEntregarPaquete.setViewportView(TablaListaInventarioCamionC);

        btnEntregarPaquetesCC.setBackground(new java.awt.Color(37, 98, 234));
        btnEntregarPaquetesCC.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEntregarPaquetesCC.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregarPaquetesCC.setText("Entregar");
        btnEntregarPaquetesCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarPaquetesCCActionPerformed(evt);
            }
        });

        btnRefreshCC.setBackground(new java.awt.Color(204, 255, 255));
        btnRefreshCC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnRefreshCC.setText("Refresh");
        btnRefreshCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondoTUIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntregarPaquetesCC)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCamionP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefreshCC))
                        .addComponent(TablaEntregarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamionP)
                    .addComponent(btnRefreshCC))
                .addGap(18, 18, 18)
                .addComponent(TablaEntregarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEntregarPaquetesCC)
                .addContainerGap(440, Short.MAX_VALUE))
            .addComponent(PanelFondoTUIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregarPaquetesCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarPaquetesCCActionPerformed
            //vehiculo.cambiarEstadoPaquete("recibido", "En Transito");
            vehiculo.cambiarEstadoPaquete("En Transito", "Listo para retiro");
            List<Paquete> paquetes = vehiculo.listarPaquetes("En Transito");
    
            // Obtener el modelo de la tabla de inventario del camión
            DefaultTableModel camionModel = (DefaultTableModel) TablaListaInventarioCamionC.getModel();
            camionModel.setRowCount(0); // Limpiar la tabla de inventario del camión
    
            // Obtener el modelo de la tabla de inventario principal
            DefaultTableModel inventarioModel = (DefaultTableModel) TablaListaInventarioCamionC.getModel();
            inventarioModel.setRowCount(0); // Limpiar la tabla de inventario principal
    
            // Agregar las filas correspondientes a TablaListaInventarioCamion
            for (Paquete paquete : paquetes) {
                Object[] row = new Object[7]; 
                row[0] = paquete.getId_paquete();
                row[1] = paquete.getTrackingNumber();
                row[2] = paquete.getPeso();
                row[3] = paquete.getTamanio();
                row[4] = paquete.getTipoEnvio();
                row[5] = paquete.getSucursalParaRecoger();
                row[6] = paquete.getSucursalAceptoPaquete();
                camionModel.addRow(row);
            }   
       // vehiculo.cambiarEstadoPaquete("En Transito", "Recibido");
        // listar tabla 1
        
    }//GEN-LAST:event_btnEntregarPaquetesCCActionPerformed

    private void btnRefreshCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCCActionPerformed
                Vehiculo vehiculo = new Vehiculo(); 
        // Obtener la lista de paquetes con el estado "recibido"
        List<Paquete> paquetes = vehiculo.listarPaquetes("En Transito");

        // Crear el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) TablaListaInventarioCamionC.getModel();
        model.setRowCount(0); // Limpiar la tabla

        // Llenar la tabla con la información de los paquetes
        for (Paquete paquete : paquetes) {
            Object[] row = new Object[7]; // Ajusta este tamaño según el número de columnas en tu tabla
            row[0] = paquete.getId_paquete();
            row[1] = paquete.getTrackingNumber();
            row[2] = paquete.getPeso();
            row[3] = paquete.getTamanio();
            row[4] = paquete.getTipoEnvio();
            row[5] = paquete.getSucursalParaRecoger();
            row[6] = paquete.getSucursalAceptoPaquete();
            model.addRow(row);
        }
    }//GEN-LAST:event_btnRefreshCCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgCamionTUIP;
    private javax.swing.JPanel PanelFondoTUIP;
    private javax.swing.JScrollPane TablaEntregarPaquete;
    private javax.swing.JTable TablaListaInventarioCamionC;
    private javax.swing.JLabel TxtCamion;
    private javax.swing.JButton btnEntregarPaquetesCC;
    private javax.swing.JToggleButton btnRefreshCC;
    private javax.swing.JLabel txtCamionP;
    private javax.swing.JLabel txtCapacidadP;
    // End of variables declaration//GEN-END:variables
}
