/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Transporte;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import BL.GestionPaquete.Paquete;
import BL.Transporte.Vehiculo;
import BL.Transporte.CamionCarga;

/**
 *
 * @author saidl
 */
public class UICamionCarga extends javax.swing.JPanel {

    Vehiculo vehiculo = new Vehiculo();
    /**
     * Creates new form UITransporte
     */
    public UICamionCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_InfoCamion = new javax.swing.JPanel();
        ImgCamion = new javax.swing.JLabel();
        TxtCamion = new javax.swing.JLabel();
        BtnActualizarCC = new javax.swing.JButton();
        TxtInventario = new javax.swing.JLabel();
        TablaInventario = new javax.swing.JScrollPane();
        TablaListaInventarioCC = new javax.swing.JTable();
        TxtInventario1 = new javax.swing.JLabel();
        TablaCargarPaquete = new javax.swing.JScrollPane();
        TablaListaInventarioCamionC = new javax.swing.JTable();
        BtnAgrergarCC = new javax.swing.JButton();
        BtnGuardarCE = new javax.swing.JButton();

        Panel_InfoCamion.setBackground(new java.awt.Color(37, 98, 234));

        ImgCamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Transporte/Imagenes/camion.jpg"))); // NOI18N

        TxtCamion.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        TxtCamion.setForeground(new java.awt.Color(255, 255, 255));
        TxtCamion.setText("CAMIÓN CARGA");

        javax.swing.GroupLayout Panel_InfoCamionLayout = new javax.swing.GroupLayout(Panel_InfoCamion);
        Panel_InfoCamion.setLayout(Panel_InfoCamionLayout);
        Panel_InfoCamionLayout.setHorizontalGroup(
            Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ImgCamion))
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(TxtCamion)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        Panel_InfoCamionLayout.setVerticalGroup(
            Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ImgCamion)
                .addGap(35, 35, 35)
                .addComponent(TxtCamion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnActualizarCC.setBackground(new java.awt.Color(37, 101, 234));
        BtnActualizarCC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnActualizarCC.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizarCC.setText("Actualizar");
        BtnActualizarCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarCCActionPerformed(evt);
            }
        });

        TxtInventario.setBackground(new java.awt.Color(37, 98, 234));
        TxtInventario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TxtInventario.setText("CAMION");

        TablaListaInventarioCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Paquete", "Peso", "Tamanio", "Remitente", "Agencia Origen", "Agencia Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaInventario.setViewportView(TablaListaInventarioCC);

        TxtInventario1.setBackground(new java.awt.Color(37, 98, 234));
        TxtInventario1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TxtInventario1.setText("INVENTARIO");

        TablaListaInventarioCamionC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Paquete", "Peso", "Tamanio", "Remitente", "Agencia Origen", "Agencia Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaCargarPaquete.setViewportView(TablaListaInventarioCamionC);

        BtnAgrergarCC.setBackground(new java.awt.Color(37, 101, 234));
        BtnAgrergarCC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnAgrergarCC.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgrergarCC.setText("Agregar");
        BtnAgrergarCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgrergarCCActionPerformed(evt);
            }
        });

        BtnGuardarCE.setBackground(new java.awt.Color(37, 101, 234));
        BtnGuardarCE.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnGuardarCE.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarCE.setText("Guardar");
        BtnGuardarCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_InfoCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardarCE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnActualizarCC)
                            .addComponent(TxtInventario)
                            .addComponent(BtnAgrergarCC)
                            .addComponent(TxtInventario1)
                            .addComponent(TablaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                            .addComponent(TablaCargarPaquete))
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtnActualizarCC)
                .addGap(22, 22, 22)
                .addComponent(TxtInventario1)
                .addGap(18, 18, 18)
                .addComponent(TablaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TxtInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TablaCargarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnAgrergarCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(BtnGuardarCE)
                .addGap(17, 17, 17))
            .addComponent(Panel_InfoCamion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgrergarCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgrergarCCActionPerformed
        vehiculo.cambiarEstadoPaquete("Listo para Cargar", "En Transito");
        //vehiculo.cambiarEstadoPaquete("Entregado", "recibido");
        //vehiculo.cambiarEstadoPaquete("Entregado", "recibido");
        List<Paquete> paquetes = vehiculo.listarPaquetes("En Transito"); // Obtener los paquet

        // Obtener el modelo de la tabla de inventario del camión
        DefaultTableModel camionModel = (DefaultTableModel) TablaListaInventarioCamionC.getModel();
        camionModel.setRowCount(0); // Limpiar la tabla de inventario del camión

        // Obtener el modelo de la tabla de inventario principal
        DefaultTableModel inventarioModel = (DefaultTableModel) TablaListaInventarioCC.getModel();
        inventarioModel.setRowCount(0); // Limpiar la tabla de inventario principal

        // Agregar las filas correspondientes a TablaListaInventarioCamion
        for (Paquete paquete : paquetes) {
            Object[] row = new Object[7]; 
            row[0] = paquete.getId_paquete();
            row[1] = paquete.getTrackingNumber();
            row[2] = paquete.getPeso();
            row[3] = paquete.getTamanio();
            row[4] = paquete.getTipoEnvio();
            row[5] = paquete.getSucursalParaRecoger();
            row[6] = paquete.getSucursalAceptoPaquete();
            camionModel.addRow(row);
        }
        //vehiculo.cambiarEstadoPaquete("Retiro Transporte", "En Transito");
              //  List Vehiculo = vehiculo.listarPaquetes("En Transito");
                // cargar tabla 1(limpiar) y 2 (Cargar)
    }//GEN-LAST:event_BtnAgrergarCCActionPerformed


    private void BtnGuardarCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCEActionPerformed
   // UITransportePaquetes uitp = new UITransportePaquetes();
    //AdminMenuPrincipal.ShowJPanel(uitp);
    }//GEN-LAST:event_BtnGuardarCEActionPerformed

    private void BtnActualizarCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarCCActionPerformed
        Vehiculo vehiculo = new Vehiculo(); 
        // Obtener la lista de paquetes con el estado "recibido"
        List<Paquete> paquetes = vehiculo.listarPaquetes("Listo para Cargar");

        // Crear el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) TablaListaInventarioCC.getModel();
        model.setRowCount(0); // Limpiar la tabla

        // Llenar la tabla con la información de los paquetes
        for (Paquete paquete : paquetes) {
            Object[] row = new Object[7]; // Ajusta este tamaño según el número de columnas en tu tabla
            row[0] = paquete.getId_paquete();
            row[1] = paquete.getTrackingNumber();
            row[2] = paquete.getPeso();
            row[3] = paquete.getTamanio();
            row[4] = paquete.getTipoEnvio();
            row[5] = paquete.getSucursalParaRecoger();
            row[6] = paquete.getSucursalAceptoPaquete();
            model.addRow(row);
        }

    }//GEN-LAST:event_BtnActualizarCCActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarCC;
    private javax.swing.JButton BtnAgrergarCC;
    private javax.swing.JButton BtnGuardarCE;
    private javax.swing.JLabel ImgCamion;
    private javax.swing.JPanel Panel_InfoCamion;
    private javax.swing.JScrollPane TablaCargarPaquete;
    private javax.swing.JScrollPane TablaInventario;
    private javax.swing.JTable TablaListaInventarioCC;
    private javax.swing.JTable TablaListaInventarioCamionC;
    private javax.swing.JLabel TxtCamion;
    private javax.swing.JLabel TxtInventario;
    private javax.swing.JLabel TxtInventario1;
    // End of variables declaration//GEN-END:variables
}
