/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Transporte;

/**
 *
 * @author saidl
 */
public class UITransporte extends javax.swing.JPanel {

    /**
     * Creates new form UITransporte
     */
    public UITransporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_InfoCamion = new javax.swing.JPanel();
        ImgCamion = new javax.swing.JLabel();
        TxtCamion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFieldModelo = new javax.swing.JTextField();
        TxtMarca = new javax.swing.JLabel();
        TxtFieldModelo1 = new javax.swing.JTextField();
        TxtDisponible = new javax.swing.JLabel();
        TxtFieldModelo2 = new javax.swing.JTextField();
        TxtDisponible1 = new javax.swing.JLabel();
        TxtFieldModelo3 = new javax.swing.JTextField();
        BtnActualizar = new javax.swing.JButton();
        TxtInventario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaListaInventario = new javax.swing.JTable();
        TxtInventario1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListaInventarioCamion = new javax.swing.JTable();
        BtnAgrergar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        Panel_InfoCamion.setBackground(new java.awt.Color(37, 98, 234));

        ImgCamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Transporte/Imagenes/camion.jpg"))); // NOI18N

        TxtCamion.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        TxtCamion.setForeground(new java.awt.Color(255, 255, 255));
        TxtCamion.setText("CAMIÓN");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo");

        TxtFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldModeloActionPerformed(evt);
            }
        });

        TxtMarca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TxtMarca.setForeground(new java.awt.Color(255, 255, 255));
        TxtMarca.setText("Marca");

        TxtFieldModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldModelo1ActionPerformed(evt);
            }
        });

        TxtDisponible.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TxtDisponible.setForeground(new java.awt.Color(255, 255, 255));
        TxtDisponible.setText("Disponible");

        TxtFieldModelo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldModelo2ActionPerformed(evt);
            }
        });

        TxtDisponible1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TxtDisponible1.setForeground(new java.awt.Color(255, 255, 255));
        TxtDisponible1.setText("Capacidad");

        TxtFieldModelo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldModelo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_InfoCamionLayout = new javax.swing.GroupLayout(Panel_InfoCamion);
        Panel_InfoCamion.setLayout(Panel_InfoCamionLayout);
        Panel_InfoCamionLayout.setHorizontalGroup(
            Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtMarca)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TxtDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFieldModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(TxtDisponible1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImgCamion)
                            .addComponent(TxtCamion))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Panel_InfoCamionLayout.setVerticalGroup(
            Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InfoCamionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ImgCamion)
                .addGap(28, 28, 28)
                .addComponent(TxtCamion)
                .addGap(33, 33, 33)
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMarca)
                    .addComponent(TxtFieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDisponible)
                    .addComponent(TxtFieldModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_InfoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDisponible1)
                    .addComponent(TxtFieldModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        BtnActualizar.setBackground(new java.awt.Color(37, 101, 234));
        BtnActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualizar");

        TxtInventario.setBackground(new java.awt.Color(37, 98, 234));
        TxtInventario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TxtInventario.setText("CAMION");

        TablaListaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Paquete", "Traking Number", "Peso", "Tamanio", "Tipo de Envio", "Direccion Destino", "Sucursal Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaListaInventario);

        TxtInventario1.setBackground(new java.awt.Color(37, 98, 234));
        TxtInventario1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TxtInventario1.setText("INVENTARIO");

        TablaListaInventarioCamion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Paquete", "Traking Number", "Peso", "Tamanio", "Tipo de Envio", "Direccion Destino", "Sucursal Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaListaInventarioCamion);

        BtnAgrergar.setBackground(new java.awt.Color(37, 101, 234));
        BtnAgrergar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnAgrergar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgrergar.setText("Agregar");
        BtnAgrergar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgrergarActionPerformed(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(37, 101, 234));
        BtnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_InfoCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnActualizar)
                            .addComponent(TxtInventario)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAgrergar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(332, 332, 332)
                    .addComponent(TxtInventario1)
                    .addContainerGap(490, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_InfoCamion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BtnActualizar)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(TxtInventario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAgrergar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(BtnGuardar)
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(TxtInventario1)
                    .addContainerGap(706, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldModeloActionPerformed

    private void TxtFieldModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldModelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldModelo1ActionPerformed

    private void TxtFieldModelo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldModelo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldModelo2ActionPerformed

    private void TxtFieldModelo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldModelo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldModelo3ActionPerformed

    private void BtnAgrergarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgrergarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgrergarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgrergar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JLabel ImgCamion;
    private javax.swing.JPanel Panel_InfoCamion;
    private javax.swing.JTable TablaListaInventario;
    private javax.swing.JTable TablaListaInventarioCamion;
    private javax.swing.JLabel TxtCamion;
    private javax.swing.JLabel TxtDisponible;
    private javax.swing.JLabel TxtDisponible1;
    private javax.swing.JTextField TxtFieldModelo;
    private javax.swing.JTextField TxtFieldModelo1;
    private javax.swing.JTextField TxtFieldModelo2;
    private javax.swing.JTextField TxtFieldModelo3;
    private javax.swing.JLabel TxtInventario;
    private javax.swing.JLabel TxtInventario1;
    private javax.swing.JLabel TxtMarca;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
