package UI.Almacenamiento;

import BL.Almacenamiento.Inventario;
import BL.GestionPaquete.Paquete;
import java.util.ArrayList;


/**
 *
 * @author jg200
 */
public class InventarioUI extends javax.swing.JPanel {

    /**
     * Creates new form InventarioUI
     */
    public InventarioUI() {
        initComponents();
        this.jTablePaquetes.setModel(Inventario.getInstancia().mostrarPaquetes(0));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaquetes = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jComboBFiltroConsulta = new javax.swing.JComboBox<>();
        jTabbedPanelMain = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTFidcargaRecepcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFpesocargaRecepcion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTFTamaniocargaRecepcion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTFRemitentecargaRecepcion = new javax.swing.JTextField();
        jTFDestinatariocargaRecepcion = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTFSucursalOrigencargaRecepcion = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTFSucursalDestinocargaRecepcion = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTFestadoRecepcion = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jBCancelarcargaRecepcion = new javax.swing.JButton();

        jTablePaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaquetes);

        jPanel12.setBackground(new java.awt.Color(254, 254, 254));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Tabla"));

        jComboBFiltroConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los Paquetes", "Paquetes En Bodega", "Paquetes Entregados", "Paquetes Transportandose", "Paquetes En Conflicto" }));
        jComboBFiltroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBFiltroConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBFiltroConsulta, 0, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBFiltroConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(254, 254, 254));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Paquetes"));

        jTFidcargaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidcargaRecepcionActionPerformed(evt);
            }
        });
        jTFidcargaRecepcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFidcargaRecepcionKeyReleased(evt);
            }
        });

        jLabel14.setText("idPaquete");

        jTFpesocargaRecepcion.setEditable(false);
        jTFpesocargaRecepcion.setFocusable(false);

        jLabel26.setText("Peso");

        jTFTamaniocargaRecepcion.setEditable(false);
        jTFTamaniocargaRecepcion.setFocusable(false);

        jLabel27.setText("Tamaño");

        jLabel28.setText("Remitente");

        jTFRemitentecargaRecepcion.setEditable(false);
        jTFRemitentecargaRecepcion.setFocusable(false);

        jTFDestinatariocargaRecepcion.setEditable(false);
        jTFDestinatariocargaRecepcion.setFocusable(false);

        jLabel29.setText("Destinatario");

        jTFSucursalOrigencargaRecepcion.setEditable(false);
        jTFSucursalOrigencargaRecepcion.setFocusable(false);

        jLabel31.setText("Sucursal Origen");

        jLabel32.setText("Sucursal Destino");

        jTFSucursalDestinocargaRecepcion.setEditable(false);
        jTFSucursalDestinocargaRecepcion.setFocusable(false);

        jLabel34.setText("Estado");

        jTFestadoRecepcion.setEditable(false);
        jTFestadoRecepcion.setFocusable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel34))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFSucursalDestinocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFestadoRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jTFDestinatariocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFRemitentecargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFSucursalOrigencargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(62, 62, 62)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFTamaniocargaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTFidcargaRecepcion)
                            .addComponent(jTFpesocargaRecepcion))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFidcargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFpesocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTamaniocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRemitentecargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDestinatariocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSucursalOrigencargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSucursalDestinocargaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jTFestadoRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jPanel14.setBackground(new java.awt.Color(254, 254, 254));

        jBCancelarcargaRecepcion.setBackground(new java.awt.Color(37, 98, 234));
        jBCancelarcargaRecepcion.setText("Cancelar");
        jBCancelarcargaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarcargaRecepcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jBCancelarcargaRecepcion)
                .addGap(82, 82, 82))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCancelarcargaRecepcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPanelMain.addTab("Datos Paquetes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanelMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPanelMain)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPanelMain.getAccessibleContext().setAccessibleName("Datos del Paquete");
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePaquetesMouseClicked
        int index = this.jComboBFiltroConsulta.getSelectedIndex();
        String id = jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 0).toString();
        String peso = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 1).toString();
        String tamanio = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 2).toString(); 
        String remitente = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 3).toString();
        String destinatario = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 4).toString(); 
        String origen = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 5).toString();
        String destino = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 6).toString(); 
        String estado = (String) jTablePaquetes.getValueAt(jTablePaquetes.getSelectedRow(), 7).toString();
        switch (index) {
            case 1:
                this.jTablePaquetes.setEnabled(true);
                this.jTFidcargaRecepcion.setText(id);
                this.jTFpesocargaRecepcion.setText(peso);
                this.jTFTamaniocargaRecepcion.setText(tamanio);
                this.jTFRemitentecargaRecepcion.setText(remitente);
                this.jTFDestinatariocargaRecepcion.setText(destinatario);
                this.jTFSucursalOrigencargaRecepcion.setText(origen);
                this.jTFSucursalDestinocargaRecepcion.setText(destino);
                this.jTFestadoRecepcion.setText(estado);
                break;
            case 2:
                this.jTablePaquetes.setEnabled(true);
             
                break;
            case 4:
                this.jTablePaquetes.setEnabled(true);
              
                break;
            default:
                this.jTablePaquetes.setEnabled(false);
                throw new AssertionError();
        }
        
    }//GEN-LAST:event_jTablePaquetesMouseClicked

    private void jComboBFiltroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBFiltroConsultaActionPerformed
        this.jTablePaquetes.setModel(Inventario.getInstancia().mostrarPaquetes(this.jComboBFiltroConsulta.getSelectedIndex()));
    }//GEN-LAST:event_jComboBFiltroConsultaActionPerformed

    private void jBCancelarcargaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarcargaRecepcionActionPerformed
        this.jTFidcargaRecepcion.setText("");
        this.jTFpesocargaRecepcion.setText("");
        this.jTFTamaniocargaRecepcion.setText("");
        this.jTFDestinatariocargaRecepcion.setText("");
        this.jTFRemitentecargaRecepcion.setText("");
        this.jTFDestinatariocargaRecepcion.setText("");
        this.jTFSucursalOrigencargaRecepcion.setText("");
        this.jTFSucursalDestinocargaRecepcion.setText("");
        this.jTFestadoRecepcion.setText("");
    }//GEN-LAST:event_jBCancelarcargaRecepcionActionPerformed

    private void jTFidcargaRecepcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFidcargaRecepcionKeyReleased
        String id = this.jTFidcargaRecepcion.getName();
        ArrayList<Paquete> paquetes_consulta = Inventario.getInstancia().getPaquetesInventario();

        Paquete paqueteEncontrado = null;
        for (Paquete paquete : paquetes_consulta) {
            if (paquete.getTracking().equals(id)) {
                paqueteEncontrado = paquete;
                break;
            }
        }

        if (paqueteEncontrado != null) {
            this.jTFpesocargaRecepcion.setText(String.valueOf(paqueteEncontrado.getPeso()));
            this.jTFTamaniocargaRecepcion.setText(String.valueOf(paqueteEncontrado.getTamanio()));
            this.jTFRemitentecargaRecepcion.setText(paqueteEncontrado.getCliente());
            this.jTFDestinatariocargaRecepcion.setText("Remitente");
            this.jTFSucursalOrigencargaRecepcion.setText(paqueteEncontrado.getSucursalOrigen());
            this.jTFSucursalDestinocargaRecepcion.setText(paqueteEncontrado.getSucursalDestino());
            this.jTFestadoRecepcion.setText("Recepción");
        } else {
            System.out.println("Paquete no encontrado con el ID: " + id);
        }
    }//GEN-LAST:event_jTFidcargaRecepcionKeyReleased

    private void jTFidcargaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidcargaRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidcargaRecepcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarcargaRecepcion;
    private javax.swing.JComboBox<String> jComboBFiltroConsulta;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDestinatariocargaRecepcion;
    private javax.swing.JTextField jTFRemitentecargaRecepcion;
    private javax.swing.JTextField jTFSucursalDestinocargaRecepcion;
    private javax.swing.JTextField jTFSucursalOrigencargaRecepcion;
    private javax.swing.JTextField jTFTamaniocargaRecepcion;
    private javax.swing.JTextField jTFestadoRecepcion;
    private javax.swing.JTextField jTFidcargaRecepcion;
    private javax.swing.JTextField jTFpesocargaRecepcion;
    private javax.swing.JTabbedPane jTabbedPanelMain;
    private javax.swing.JTable jTablePaquetes;
    // End of variables declaration//GEN-END:variables
}
